# ./.build/velopack.yml
version: "3"

vars:
  PUBLISH_DIR: "{{.OUTPUT_DIR}}/publish/{{.RID}}"
  RELEASES_DIR: "{{.OUTPUT_DIR}}/releases"

tasks:
  pack:
    desc: "Packages the published application using Velopack"
    preconditions:
      - sh: |
          {{if eq .OS "windows"}}
            powershell -Command "exit !(Test-Path '{{.ICON_PATH}}' -PathType Leaf)"
          {{else}}
            [ -f '{{.ICON_PATH}}' ]
          {{end}}
        msg: "Velopack icon not found at '{{.ICON_PATH}}'. Check ICON_PATH in .env."
    cmds:
      - |
        vpk pack \
          --packId {{.APP_NAME}} \
          --packVersion {{.APP_VERSION}} \
          --packDir "{{.PUBLISH_DIR}}" \
          --mainExe {{if .MAIN_EXE}}{{.MAIN_EXE}}{{else}}{{.APP_NAME}}.exe{{end}} \
          --packAuthors "{{.COMPANY_NAME}}" \
          --packTitle "{{.APP_NAME}}" \
          --outputDir "{{.RELEASES_DIR}}" \
          --runtime {{.RID}} \
          --icon "{{.ICON_PATH}}"
